//! Per-file function batch emitter (EMIT-03) with rayon parallelism (EMIT-15).
//!
//! Splits decoded functions into groups of `batch_size` (default: 50) and emits
//! each group as a separate .cpp file in the `generated/` subdirectory.
//! Uses rayon `par_iter` for parallel codegen; sorts output by vaddr for
//! deterministic file content (Pitfall 5 in RESEARCH.md).
//!
//! Also generates `funcs.h` — a forward-declaration header included by all .cpp
//! files. This prevents C++ compilation errors when mid-entry wrappers and their
//! parent functions are in different batch files (Pitfall 4 in RESEARCH.md).
use rayon::prelude::*;
use psp_parser::analysis_json::JsonFunction;
use crate::sanitize::sanitize_identifier;

/// Result of a batch emission run.
pub struct BatchOutput {
    /// Vec of (filename, content) pairs for each generated .cpp file.
    /// Filenames are like "generated/batch_000.cpp", sorted by batch index.
    pub cpp_files: Vec<(String, String)>,
    /// Content of `funcs.h` — forward declarations for all functions.
    pub funcs_h: String,
}

/// Emit all functions in parallel batches.
///
/// `functions`: full function list from analysis.json (sorted by address).
/// `batch_size`: functions per .cpp file (default 50, per EMIT-03).
/// `mid_entry_fwd_decls`: forward declarations from emit_mid_entry_wrappers.
/// `per_func_emit`: callback invoked once per function; returns the C++ body string
///   for that function. The caller (psp-cli run_recompile) supplies the decode+emit
///   pipeline here, keeping batch.rs free of decoder/emitter dependencies.
pub fn emit_function_batches(
    functions: &[JsonFunction],
    batch_size: usize,
    mid_entry_fwd_decls: &str,
    per_func_emit: impl Fn(&JsonFunction) -> String + Sync,
    name_overrides: &std::collections::HashMap<u32, String>,
) -> anyhow::Result<BatchOutput> {
    // Sort functions by virtual address for deterministic output (EMIT-15)
    let mut sorted: Vec<&JsonFunction> = functions.iter().collect();
    sorted.sort_by_key(|f| {
        u64::from_str_radix(f.address.trim_start_matches("0x"), 16).unwrap_or(0)
    });

    let effective_batch_size = batch_size.max(1);
    let batches: Vec<Vec<&JsonFunction>> = sorted
        .chunks(effective_batch_size)
        .map(|c| c.to_vec())
        .collect();

    // Generate funcs.h — forward declarations for all functions + mid-entry wrappers
    let funcs_h = {
        let mut h = String::with_capacity(functions.len() * 60 + 512);
        h.push_str("#pragma once\n");
        h.push_str("#include \"recomp.h\"\n\n");
        h.push_str("// Forward declarations for all recompiled functions\n");
        for func in &sorted {
            let addr: u32 = u64::from_str_radix(
                func.address.trim_start_matches("0x"), 16
            ).unwrap_or(0) as u32;
            let cpp_name = name_overrides
                .get(&addr)
                .map(|n| sanitize_identifier(n))
                .unwrap_or_else(|| sanitize_identifier(&func.name));
            h.push_str(&format!(
                "RECOMP_FUNC void {}(uint8_t* rdram, recomp_context* ctx);\n",
                cpp_name
            ));
        }
        h.push_str("\n// Mid-entry wrapper forward declarations\n");
        h.push_str(mid_entry_fwd_decls);
        h
    };

    // Parallel codegen: each batch produces (batch_idx, cpp_content)
    let results: Vec<anyhow::Result<(usize, String)>> = batches
        .into_par_iter()
        .enumerate()
        .map(|(idx, batch)| {
            let mut content = String::with_capacity(batch.len() * 512 + 256);
            content.push_str("// Generated by psprecomp — do not edit\n");
            content.push_str("#include \"recomp.h\"\n");
            content.push_str("#include \"funcs.h\"\n\n");
            for func in &batch {
                // Delegate content generation entirely to the caller-supplied callback.
                // The callback returns a complete C++ function definition string
                // (including signature, braces, and body).
                let func_cpp = per_func_emit(func);
                content.push_str(&func_cpp);
                content.push('\n');
            }
            Ok((idx, content))
        })
        .collect();

    // Sort output by batch index (rayon processes in arbitrary order)
    let mut indexed: Vec<(usize, String)> = results
        .into_iter()
        .collect::<anyhow::Result<Vec<_>>>()?;
    indexed.sort_by_key(|(idx, _)| *idx);

    let cpp_files = indexed
        .into_iter()
        .map(|(idx, content)| (format!("generated/batch_{idx:04}.cpp"), content))
        .collect();

    Ok(BatchOutput { cpp_files, funcs_h })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_func(addr: u32, name: &str) -> JsonFunction {
        JsonFunction {
            name: name.into(),
            address: format!("0x{addr:08X}"),
            size: 16,
            is_external: false,
            is_thunk: false,
            source: "ghidra".into(),
        }
    }

    // Stub callback: produces a minimal function definition for testing.
    fn stub_emit(func: &JsonFunction) -> String {
        let name = sanitize_identifier(&func.name);
        format!(
            "RECOMP_FUNC void {}(uint8_t* rdram, recomp_context* ctx) {{\n    /* stub */\n}}\n",
            name
        )
    }

    #[test]
    fn batches_split_correctly() {
        let funcs: Vec<JsonFunction> = (0..10)
            .map(|i| make_func(0x08804000 + i * 4, &format!("FUN_{i:08X}")))
            .collect();
        let result = emit_function_batches(&funcs, 3, "", stub_emit, &std::collections::HashMap::new()).unwrap();
        // 10 functions / 3 per batch = 4 batches (3+3+3+1)
        assert_eq!(result.cpp_files.len(), 4);
    }

    #[test]
    fn output_sorted_by_batch_index() {
        let funcs: Vec<JsonFunction> = (0..6)
            .map(|i| make_func(0x08804000 + i * 4, &format!("FUN_{i}")))
            .collect();
        let result = emit_function_batches(&funcs, 2, "", stub_emit, &std::collections::HashMap::new()).unwrap();
        let names: Vec<&str> = result.cpp_files.iter().map(|(n, _)| n.as_str()).collect();
        assert_eq!(names[0], "generated/batch_0000.cpp");
        assert_eq!(names[1], "generated/batch_0001.cpp");
        assert_eq!(names[2], "generated/batch_0002.cpp");
    }

    #[test]
    fn funcs_h_contains_all_decls() {
        let funcs = vec![
            make_func(0x08804000, "FUN_08804000"),
            make_func(0x08810000, "FUN_08810000"),
        ];
        let result = emit_function_batches(&funcs, 50, "", stub_emit, &std::collections::HashMap::new()).unwrap();
        assert!(result.funcs_h.contains("FUN_08804000"));
        assert!(result.funcs_h.contains("FUN_08810000"));
        assert!(result.funcs_h.contains("#pragma once"));
    }

    #[test]
    fn batch_size_one_is_valid() {
        let funcs = vec![make_func(0x08804000, "FUN_08804000")];
        let result = emit_function_batches(&funcs, 1, "", stub_emit, &std::collections::HashMap::new()).unwrap();
        assert_eq!(result.cpp_files.len(), 1);
    }

    #[test]
    fn callback_output_appears_in_batch_file() {
        // Verify the callback's return value ends up verbatim in the .cpp content.
        let funcs = vec![make_func(0x08804000, "FUN_08804000")];
        let result = emit_function_batches(&funcs, 50, "", |_f| {
            "RECOMP_FUNC void SENTINEL(uint8_t* rdram, recomp_context* ctx) {}\n".into()
        }, &std::collections::HashMap::new()).unwrap();
        assert!(result.cpp_files[0].1.contains("SENTINEL"),
            "callback output must appear verbatim in batch .cpp");
    }
}
