//! CMakeLists.txt emitter for the generated C++ project.
//!
//! Produces a CMake 3.20+ project targeting C++17 with Clang.
//! The generated project compiles as a static library (`add_library STATIC`).
//! EMIT-14 requirement: cmake_minimum_required(3.20), C++17, Clang target warning.
//! Source: RESEARCH.md §CMakeLists.txt Generation.

/// Emit `CMakeLists.txt` content for the generated recompilation project.
///
/// `module_name`: used as the CMake project name and library name.
pub fn emit_cmake_lists(module_name: &str) -> String {
    format!(
r#"# Generated by psprecomp recompile — do not edit
cmake_minimum_required(VERSION 3.20)
project({module_name}_recomp CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Clang only — RECOMP_FUNC (__attribute__((noinline))) behavior differs on GCC/MSVC
if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    message(WARNING "Non-Clang compiler detected. RECOMP_FUNC behavior may differ.")
endif()

# Collect all generated per-function translation units (batch files only)
file(GLOB RECOMP_SOURCES "${{CMAKE_CURRENT_SOURCE_DIR}}/generated/batch_*.cpp")

# Add fixed support files
list(APPEND RECOMP_SOURCES
    "${{CMAKE_CURRENT_SOURCE_DIR}}/dispatch.cpp"
    "${{CMAKE_CURRENT_SOURCE_DIR}}/data_sections.cpp"
    "${{CMAKE_CURRENT_SOURCE_DIR}}/init_array.cpp"
    "${{CMAKE_CURRENT_SOURCE_DIR}}/mid_entries.cpp"
    "${{CMAKE_CURRENT_SOURCE_DIR}}/syscall_table.cpp"
)

add_library({module_name}_recomp STATIC ${{RECOMP_SOURCES}})
# Stable alias: the runtime links `psp::recomp` so it never needs to know
# the per-game module name (issue #47 Phase 1).
add_library(psp::recomp ALIAS {module_name}_recomp)
target_include_directories({module_name}_recomp PUBLIC
    "${{CMAKE_CURRENT_SOURCE_DIR}}/include"
    "${{CMAKE_CURRENT_SOURCE_DIR}}"
)
target_compile_options({module_name}_recomp PRIVATE
    -O2
    -fno-lto
    -fno-strict-aliasing
)
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cmake_contains_required_elements() {
        let result = emit_cmake_lists("patapon");
        assert!(result.contains("cmake_minimum_required(VERSION 3.20)"));
        assert!(result.contains("set(CMAKE_CXX_STANDARD 17)"));
        assert!(result.contains("Clang"));
        assert!(result.contains("dispatch.cpp"));
        assert!(result.contains("data_sections.cpp"));
        assert!(result.contains("mid_entries.cpp"));
        // Generated NID binding table (issue #40) is a fixed support file:
        // the runtime's psp_hle_init() links recomp_nid_stubs from it.
        assert!(result.contains("syscall_table.cpp"));
        assert!(result.contains("-fno-lto"));
        // funcs.h lives at output root, not under include/ — root must be in include path
        assert!(result.contains("${CMAKE_CURRENT_SOURCE_DIR}\""));
    }

    #[test]
    fn cmake_uses_module_name() {
        let result = emit_cmake_lists("patapon");
        assert!(result.contains("patapon_recomp"));
    }

    #[test]
    fn cmake_defines_stable_alias() {
        // The runtime links `psp::recomp` regardless of the module name
        // (issue #47 Phase 1) — the alias must always be emitted.
        let result = emit_cmake_lists("boot_dec");
        assert!(result.contains("add_library(psp::recomp ALIAS boot_dec_recomp)"));
    }
}
