//! Data sections emitter — produces `data_sections.cpp`.
//!
//! Embeds all PT_LOAD segments as `static const uint8_t[]` arrays.
//! Segment data in analysis.json is base64-encoded (`data_b64` field).
//! BSS bytes (p_memsz > p_filesz) are already zeroed in the base64 payload.
//!
//! CRITICAL: Always decode base64 before emitting. The `data_b64` field is
//! NOT raw bytes — it is Base64Standard encoded (Pitfall 6 in RESEARCH.md).
use base64::Engine as _;
use base64::engine::general_purpose::STANDARD as B64;
use psp_parser::analysis_json::JsonSegment;

/// Emit `data_sections.cpp` content from all PT_LOAD segments.
///
/// Each segment emits:
/// - `static const uint8_t seg_XXXXXXXX[] = { 0xNN, ... };`
/// - A `psp_init_data_sections(uint8_t* rdram)` function that memcpys all
///   segments into rdram at their base virtual addresses.
pub fn emit_data_sections(segments: &[JsonSegment]) -> anyhow::Result<String> {
    let mut out = String::with_capacity(segments.len() * 1024 + 4096);
    out.push_str("// Generated by psprecomp — do not edit\n");
    out.push_str("#include <cstdint>\n");
    out.push_str("#include <cstring>\n\n");

    let mut seg_names: Vec<(u32, String, usize)> = Vec::new();

    for seg in segments {
        let vaddr: u32 = u64::from_str_radix(
            seg.p_vaddr.trim_start_matches("0x"), 16
        ).unwrap_or(0) as u32;

        // Decode base64 — this is the critical step (Pitfall 6)
        let raw = B64.decode(&seg.data_b64)
            .map_err(|e| anyhow::anyhow!("base64 decode failed for seg 0x{vaddr:08X}: {e}"))?;

        let arr_name = format!("seg_{vaddr:08X}");
        out.push_str(&format!(
            "static const uint8_t {}[{}] = {{\n",
            arr_name, raw.len()
        ));

        // Emit bytes in rows of 16
        for chunk in raw.chunks(16) {
            out.push_str("    ");
            for b in chunk {
                out.push_str(&format!("0x{b:02X},"));
            }
            out.push('\n');
        }
        out.push_str("};\n\n");

        seg_names.push((vaddr, arr_name, raw.len()));
    }

    // psp_init_data_sections() — called before any game thread starts
    out.push_str("void psp_init_data_sections(uint8_t* rdram) {\n");
    for (vaddr, arr_name, size) in &seg_names {
        out.push_str(&format!(
            "    std::memcpy(rdram + (0x{vaddr:08X}U & 0x07FFFFFFU), {arr_name}, {size}U);\n"
        ));
    }
    out.push_str("}\n");

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use base64::engine::general_purpose::STANDARD as B64;

    #[test]
    fn emit_empty_segments() {
        let result = emit_data_sections(&[]).unwrap();
        assert!(result.contains("psp_init_data_sections"));
    }

    #[test]
    fn emit_single_segment_decoded() {
        use psp_parser::analysis_json::JsonSegment;
        let data = vec![0xDEu8, 0xAD, 0xBE, 0xEF];
        let seg = JsonSegment {
            p_vaddr: "0x08804000".into(),
            p_filesz: 4,
            p_memsz: 4,
            p_flags: 5,
            data_b64: B64.encode(&data),
        };
        let result = emit_data_sections(&[seg]).unwrap();
        assert!(result.contains("seg_08804000"), "array name from vaddr");
        assert!(result.contains("0xDE"), "decoded byte in output");
        assert!(result.contains("(0x08804000U & 0x07FFFFFFU)"), "masked vaddr in memcpy call");
    }
}
