//! Dispatch table emitter — produces `dispatch.cpp`.
//!
//! The dispatch table maps PSP virtual addresses to C++ function pointers.
//! `RECOMP_LOOKUP(vaddr)` uses it for indirect calls and cross-section jumps.
//! Address 0x00000000 maps to a no-op function (safe sentinel for unresolved calls).
use psp_parser::analysis_json::{JsonFunction, JsonMidEntry};

/// Emit the full `dispatch.cpp` file content.
///
/// `functions`: all decoded functions (from analysis.json).
/// `mid_entries`: mid-function entry wrappers (generated in Plan 02-06).
/// Returns the complete C++ source as a `String`.
pub fn emit_dispatch_table(
    functions: &[JsonFunction],
    mid_entries: &[JsonMidEntry],
    module_name: &str,
    name_overrides: &std::collections::HashMap<u32, String>,
) -> String {
    let _ = module_name; // used by caller for naming context
    let mut out = String::with_capacity(functions.len() * 60 + 4096);
    out.push_str("// Generated by psprecomp — do not edit\n");
    out.push_str("#include \"recomp.h\"\n");
    out.push_str("#include \"funcs.h\"\n\n");
    out.push_str("using FuncPtr = void(*)(uint8_t*, recomp_context*);\n\n");
    out.push_str("static void noop_func(uint8_t*, recomp_context*) {}\n\n");
    out.push_str("static std::unordered_map<uint32_t, FuncPtr> s_dispatch;\n\n");

    // psp_init_dispatch_table() populates the map at startup
    out.push_str("void psp_init_dispatch_table() {\n");
    out.push_str(&format!("    s_dispatch.reserve({});\n",
        functions.len() + mid_entries.len() + 1));
    out.push_str("    s_dispatch[0x00000000U] = noop_func;\n");

    for func in functions {
        let addr: u32 = u64::from_str_radix(
            func.address.trim_start_matches("0x"), 16
        ).unwrap_or(0) as u32;
        // Use deduplicated name if available, otherwise sanitize the original
        let cpp_name = name_overrides
            .get(&addr)
            .map(|n| crate::sanitize::sanitize_identifier(n))
            .unwrap_or_else(|| crate::sanitize::sanitize_identifier(&func.name));
        out.push_str(&format!(
            "    s_dispatch[0x{addr:08X}U] = {cpp_name};\n"
        ));
    }

    // Mid-entry wrappers (generated by Plan 02-06's emit_mid_entry_wrappers)
    for me in mid_entries {
        let addr: u32 = u64::from_str_radix(
            me.addr.trim_start_matches("0x"), 16
        ).unwrap_or(0) as u32;
        let wrapper_name = format!("func_{addr:08X}_entry");
        out.push_str(&format!(
            "    s_dispatch[0x{addr:08X}U] = {wrapper_name};\n"
        ));
    }

    out.push_str("}\n\n");

    // Extern miss handler — provided by the runtime's psp_dispatch.cpp
    out.push_str("extern FuncPtr psp_on_lookup_miss(uint32_t vaddr);\n\n");

    // RECOMP_LOOKUP — the entry point called by emitted indirect calls
    out.push_str("FuncPtr RECOMP_LOOKUP(uint32_t vaddr) {\n");
    out.push_str("    auto it = s_dispatch.find(vaddr);\n");
    out.push_str("    if (it == s_dispatch.end()) { return psp_on_lookup_miss(vaddr); }\n");
    out.push_str("    return it->second;\n");
    out.push_str("}\n\n");

    // psp_dispatch_register — allows runtime HLE to override dispatch entries
    // Used by Phase 4 HLE to replace import stub no-ops with HLE implementations
    out.push_str("void psp_dispatch_register(uint32_t vaddr, FuncPtr fn) {\n");
    out.push_str("    s_dispatch[vaddr] = fn;\n");
    out.push_str("}\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dispatch_contains_noop() {
        let result = emit_dispatch_table(&[], &[], "test", &std::collections::HashMap::new());
        assert!(result.contains("0x00000000U] = noop_func"));
        assert!(result.contains("RECOMP_LOOKUP"));
        assert!(result.contains(".reserve("));
    }

    #[test]
    fn dispatch_miss_calls_extern_handler() {
        let result = emit_dispatch_table(&[], &[], "test", &std::collections::HashMap::new());
        assert!(
            result.contains("psp_on_lookup_miss"),
            "miss path must call psp_on_lookup_miss"
        );
        assert!(
            result.contains("extern FuncPtr psp_on_lookup_miss"),
            "must declare extern psp_on_lookup_miss"
        );
        assert!(
            !result.contains("return noop_func;"),
            "miss path must NOT return noop_func directly"
        );
    }
}
