//! `output/include/recomp_game_config.h` — generated per-game choices
//! (issue #46, #47 Phase 4).
//!
//! Carries the manifest's runtime-relevant keys so the runtime never parses
//! TOML. Written by `psprecomp recompile` next to `recomp_module.h`; emitted
//! with no-op defaults when recompile runs without `--config` (zero-manifest
//! builds stay fully generic). The runtime guards the include so output dirs
//! generated before Phase 4 still build.

/// Per-game choices resolved from the `--config` manifest (game.toml).
/// Defaults (no manifest) are the generic no-op values.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GameChoices {
    /// `[game] id` ("" with no manifest). Boot-time mismatch guard compares
    /// this against the compiled-in `psp_game_module()->id`.
    pub game_id: String,
    /// `[boot] boot_path` (PSP-universal default when unset).
    pub boot_path: String,
    /// `[module] heap_base` pin; 0 = use the RECOMP_HEAP_BASE align policy.
    pub heap_override: u32,
    /// `[runtime] asset_layer == "bnd"`.
    pub asset_layer_bnd: bool,
}

impl Default for GameChoices {
    fn default() -> Self {
        GameChoices {
            game_id: String::new(),
            boot_path: "disc0:/PSP_GAME/SYSDIR/BOOT.BIN".into(),
            heap_override: 0,
            asset_layer_bnd: false,
        }
    }
}

/// Escape a manifest string for a C string literal.
fn c_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            c if (' '..='~').contains(&c) => out.push(c),
            c => {
                for b in c.to_string().bytes() {
                    out.push_str(&format!("\\x{b:02X}"));
                }
            }
        }
    }
    out
}

/// Render the generated header text.
pub fn emit_game_config_header(g: &GameChoices) -> String {
    format!(
        "// Generated by `psprecomp recompile` (issues #46/#47 Phase 4). DO NOT EDIT.\n\
         // Per-game choices from the --config manifest (games/<id>/game.toml);\n\
         // generic no-op defaults when recompile ran without --config.\n\
         #pragma once\n\
         #define RECOMP_GAME_ID         \"{}\" /* \"\" = no manifest */\n\
         #define RECOMP_BOOT_PATH       \"{}\"\n\
         #define RECOMP_HEAP_OVERRIDE   0x{:08X}U /* 0 = RECOMP_HEAP_BASE align policy */\n\
         #define RECOMP_ASSET_LAYER_BND {} /* [runtime] asset_layer == \"bnd\" */\n",
        c_escape(&g.game_id),
        c_escape(&g.boot_path),
        g.heap_override,
        if g.asset_layer_bnd { 1 } else { 0 },
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn zero_manifest_defaults_are_noop() {
        let h = emit_game_config_header(&GameChoices::default());
        assert!(h.contains("#define RECOMP_GAME_ID         \"\""));
        assert!(h.contains(
            "#define RECOMP_BOOT_PATH       \"disc0:/PSP_GAME/SYSDIR/BOOT.BIN\""
        ));
        assert!(h.contains("#define RECOMP_HEAP_OVERRIDE   0x00000000U"));
        assert!(h.contains("#define RECOMP_ASSET_LAYER_BND 0"));
    }

    #[test]
    fn patapon_manifest_choices_rendered() {
        let g = GameChoices {
            game_id: "patapon".into(),
            boot_path: "disc0:/PSP_GAME/SYSDIR/BOOT.BIN".into(),
            heap_override: 0,
            asset_layer_bnd: true,
        };
        let h = emit_game_config_header(&g);
        assert!(h.contains("#define RECOMP_GAME_ID         \"patapon\""));
        assert!(h.contains("#define RECOMP_ASSET_LAYER_BND 1"));
    }

    #[test]
    fn strings_are_c_escaped() {
        let g = GameChoices {
            game_id: "we\"ird".into(),
            ..GameChoices::default()
        };
        let h = emit_game_config_header(&g);
        assert!(h.contains(r#""we\"ird""#));
    }
}
