//! Static constructor call emitter — produces `psp_call_constructors()` in a .cpp file.
//!
//! Patapon BOOT.BIN has 4,600 constructors in analysis.json.constructors.
//! They must be called in address order BEFORE any game thread is created.
//! V1 lesson: missing this call leaves vtables empty and singletons uninitialized.
//! Source: RESEARCH.md EMIT-06; PITFALLS.md Pitfall 2.

/// Emit `init_array.cpp` containing `psp_call_constructors(rdram, ctx)`.
///
/// `constructors`: list of hex address strings from analysis.json.constructors.
/// Emits calls via RECOMP_LOOKUP in ascending address order.
pub fn emit_psp_call_constructors(constructors: &[String]) -> String {
    let mut addrs: Vec<u32> = constructors.iter().filter_map(|s| {
        u64::from_str_radix(s.trim_start_matches("0x"), 16)
            .ok()
            .map(|v| v as u32)
    }).collect();
    addrs.sort_unstable(); // ascending address order

    let mut out = String::with_capacity(addrs.len() * 50 + 512);
    out.push_str("// Generated by psprecomp — do not edit\n");
    out.push_str("#include \"recomp.h\"\n\n");

    out.push_str("void psp_call_constructors(uint8_t* rdram, recomp_context* ctx) {\n");
    for addr in &addrs {
        out.push_str(&format!(
            "    RECOMP_LOOKUP(0x{addr:08X}U)(rdram, ctx);\n"
        ));
    }
    out.push_str("}\n");

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn constructors_in_address_order() {
        let ctors = vec![
            "0x08810000".to_string(),
            "0x08804000".to_string(), // lower address — should appear first
        ];
        let result = emit_psp_call_constructors(&ctors);
        let pos_8804 = result.find("0x08804000").unwrap();
        let pos_8810 = result.find("0x08810000").unwrap();
        assert!(pos_8804 < pos_8810, "lower address must appear first");
    }

    #[test]
    fn empty_constructors_still_valid() {
        let result = emit_psp_call_constructors(&[]);
        assert!(result.contains("psp_call_constructors"));
        assert!(result.contains("recomp_context"));
    }
}
