//! Mid-function entry point wrapper emitter (EMIT-09).
//!
//! For each mid-entry in analysis.json, generates a thin wrapper function that
//! calls the parent function from the beginning. This allows other functions to
//! use `jal mid_entry_addr` which redirects to the parent entry, letting the parent
//! function use a C++ `goto` to jump to the mid-entry label.
//!
//! CRITICAL: Sanitize the parent function name BEFORE generating the wrapper.
//! The wrapper must match the parent's actual C++ identifier (Pitfall 3 in RESEARCH.md).
//!
//! Pattern:
//!   void func_XXXXXXXX_entry(uint8_t* rdram, recomp_context* ctx) {
//!       FUN_PPPPPPPP(rdram, ctx);
//!   }
use psp_parser::analysis_json::JsonMidEntry;
use crate::sanitize::sanitize_identifier;

/// Build a map from parent_addr (u32) to parent cpp_name for all functions.
/// Needed to look up the parent's sanitized C++ name given a mid-entry's parent_addr.
pub fn build_parent_name_map(
    functions: &[psp_parser::analysis_json::JsonFunction],
) -> std::collections::HashMap<u32, String> {
    functions.iter().filter_map(|f| {
        let addr: u32 = u64::from_str_radix(
            f.address.trim_start_matches("0x"), 16
        ).ok()? as u32;
        Some((addr, sanitize_identifier(&f.name)))
    }).collect()
}

/// Emit mid-entry wrapper functions into a single `mid_entries.cpp` string.
///
/// Each wrapper: `void func_{addr:08X}_entry(uint8_t* rdram, recomp_context* ctx)`
/// calling the parent function by its sanitized C++ name.
///
/// Returns (mid_entries_cpp, funcs_h_additions) where the latter contains
/// forward declarations for these wrapper functions to add to `funcs.h`.
pub fn emit_mid_entry_wrappers(
    mid_entries: &[JsonMidEntry],
    parent_name_map: &std::collections::HashMap<u32, String>,
) -> (String, String) {
    let mut cpp = String::with_capacity(mid_entries.len() * 120 + 256);
    let mut fwd = String::with_capacity(mid_entries.len() * 80);

    cpp.push_str("// Generated by psprecomp — do not edit\n");
    cpp.push_str("#include \"recomp.h\"\n");
    cpp.push_str("#include \"funcs.h\"\n\n");

    for me in mid_entries {
        let entry_addr: u32 = u64::from_str_radix(
            me.addr.trim_start_matches("0x"), 16
        ).unwrap_or(0) as u32;
        let parent_addr: u32 = u64::from_str_radix(
            me.parent_addr.trim_start_matches("0x"), 16
        ).unwrap_or(0) as u32;

        let wrapper_name = format!("func_{entry_addr:08X}_entry");
        let parent_name = parent_name_map
            .get(&parent_addr)
            .cloned()
            // Use FUN_ prefix + lowercase hex to match Ghidra's naming convention
            .unwrap_or_else(|| format!("FUN_{parent_addr:08x}"));

        let sig = format!(
            "RECOMP_FUNC void {}(uint8_t* rdram, recomp_context* ctx)",
            wrapper_name
        );
        cpp.push_str(&format!("{sig} {{\n"));
        cpp.push_str(&format!("    ctx->entry_point = 0x{entry_addr:08X}U;\n"));
        cpp.push_str(&format!("    {parent_name}(rdram, ctx);\n"));
        cpp.push_str("    ctx->entry_point = 0;\n");
        cpp.push_str("}\n\n");

        // Forward declaration for funcs.h
        fwd.push_str(&format!("{sig};\n"));
    }

    (cpp, fwd)
}

#[cfg(test)]
mod tests {
    use super::*;
    use psp_parser::analysis_json::JsonMidEntry;

    #[test]
    fn wrapper_uses_sanitized_parent_name() {
        let me = JsonMidEntry {
            addr: "0x08810040".into(),
            parent_addr: "0x08810000".into(),
        };
        let mut parent_map = std::collections::HashMap::new();
        parent_map.insert(0x08810000u32, "FUN_08810000".into());
        let (cpp, fwd) = emit_mid_entry_wrappers(&[me], &parent_map);
        assert!(cpp.contains("func_08810040_entry"), "wrapper name from entry addr");
        assert!(cpp.contains("ctx->entry_point = 0x08810040U;"), "sets entry_point before parent call");
        assert!(cpp.contains("FUN_08810000(rdram, ctx)"), "parent call uses sanitized name");
        assert!(cpp.contains("ctx->entry_point = 0;"), "clears entry_point after parent call");
        assert!(fwd.contains("func_08810040_entry"), "forward decl in funcs.h additions");
    }

    #[test]
    fn wrapper_fallback_when_parent_missing() {
        let me = JsonMidEntry {
            addr: "0x08810040".into(),
            parent_addr: "0x08810000".into(),
        };
        let parent_map = std::collections::HashMap::new(); // parent not in map
        let (cpp, _) = emit_mid_entry_wrappers(&[me], &parent_map);
        // Should fall back to FUN_{parent_addr:08x} (Ghidra lowercase hex naming)
        assert!(cpp.contains("FUN_08810000(rdram, ctx)"));
    }
}
