//! `output/include/recomp_module.h` — generated module facts (issue #47 P2).
//!
//! Carries the binary facts the runtime boot path needs (module identity,
//! GP, text extent, first load segment, heap base, constructor probe) so the
//! runtime contains no per-game constants. Written by `psprecomp recompile`
//! next to `recomp_fingerprint.h`; the runtime hard-includes it (post-Phase-2
//! outputs always have it, and recompile hard-errors on an analysis.json
//! without module facts).

/// Module facts resolved from analysis.json (`module{}`, `segments[0]`,
/// `heap_base`, `constructors[]`). All addresses are plain u32 here; the
/// hex-string convention applies to the JSON only.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModuleFacts {
    /// SceModuleInfo name (e.g. "Labo"). Emitted as a C string literal.
    pub name: String,
    /// Module entry point (load_base + e_entry).
    pub entry: u32,
    /// $gp from SceModuleInfo.
    pub gp: u32,
    /// text_addr (PPSSPP ElfReader semantics — see psp-parser elf::text_extent).
    pub text_start: u32,
    /// text_size (PPSSPP ElfReader semantics).
    pub text_size: u32,
    /// First PT_LOAD segment vaddr (boot data-section probe target).
    pub seg0_vaddr: u32,
    /// First PT_LOAD segment p_memsz.
    pub seg0_memsz: u32,
    /// analysis.json heap_base (first 64K-aligned address past the image).
    pub heap_base: u32,
    /// constructors[] length.
    pub ctor_count: u32,
    /// constructors[0], or 0 when ctor_count == 0 (boot dispatch probe).
    pub first_ctor: u32,
}

/// Escape a module name for a C string literal (defensive: SceModuleInfo
/// names are ASCII identifiers in practice, but never trust binary input).
fn c_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            c if (' '..='~').contains(&c) => out.push(c),
            c => {
                for b in c.to_string().bytes() {
                    out.push_str(&format!("\\x{b:02X}"));
                }
            }
        }
    }
    out
}

/// Render the generated header text.
pub fn emit_module_header(f: &ModuleFacts) -> String {
    format!(
        "// Generated by `psprecomp recompile` (issue #47 Phase 2). DO NOT EDIT.\n\
         // Binary facts from analysis.json — regenerate output/ to refresh.\n\
         #pragma once\n\
         #define RECOMP_MODULE_NAME       \"{}\"\n\
         #define RECOMP_MODULE_ENTRY      0x{:08X}U\n\
         #define RECOMP_MODULE_GP         0x{:08X}U\n\
         #define RECOMP_MODULE_TEXT_START 0x{:08X}U\n\
         #define RECOMP_MODULE_TEXT_SIZE  0x{:08X}U\n\
         #define RECOMP_SEG0_VADDR        0x{:08X}U\n\
         #define RECOMP_SEG0_MEMSZ        0x{:08X}U\n\
         #define RECOMP_HEAP_BASE         0x{:08X}U\n\
         #define RECOMP_CTOR_COUNT        {}U\n\
         #define RECOMP_FIRST_CTOR        0x{:08X}U /* 0 when CTOR_COUNT == 0 */\n",
        c_escape(&f.name),
        f.entry,
        f.gp,
        f.text_start,
        f.text_size,
        f.seg0_vaddr,
        f.seg0_memsz,
        f.heap_base,
        f.ctor_count,
        f.first_ctor,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn patapon_facts() -> ModuleFacts {
        ModuleFacts {
            name: "Labo".into(),
            entry: 0x089A_CCD0,
            gp: 0x08A5_0D20,
            text_start: 0x0880_4000,
            text_size: 0x001D_4E04,
            seg0_vaddr: 0x0880_4000,
            seg0_memsz: 0x002D_8400,
            heap_base: 0x08AE_0000,
            ctor_count: 4600,
            first_ctor: 0x0880_4CE8,
        }
    }

    #[test]
    fn header_carries_every_fact_macro() {
        let h = emit_module_header(&patapon_facts());
        assert!(h.contains("#pragma once"));
        assert!(h.contains("#define RECOMP_MODULE_NAME       \"Labo\"\n"));
        assert!(h.contains("#define RECOMP_MODULE_ENTRY      0x089ACCD0U\n"));
        assert!(h.contains("#define RECOMP_MODULE_GP         0x08A50D20U\n"));
        assert!(h.contains("#define RECOMP_MODULE_TEXT_START 0x08804000U\n"));
        assert!(h.contains("#define RECOMP_MODULE_TEXT_SIZE  0x001D4E04U\n"));
        assert!(h.contains("#define RECOMP_SEG0_VADDR        0x08804000U\n"));
        assert!(h.contains("#define RECOMP_SEG0_MEMSZ        0x002D8400U\n"));
        assert!(h.contains("#define RECOMP_HEAP_BASE         0x08AE0000U\n"));
        assert!(h.contains("#define RECOMP_CTOR_COUNT        4600U\n"));
        assert!(h.contains("#define RECOMP_FIRST_CTOR        0x08804CE8U"));
    }

    #[test]
    fn module_name_is_c_escaped() {
        let mut f = patapon_facts();
        f.name = "we\"ird\\mod\u{7f}".into();
        let h = emit_module_header(&f);
        assert!(h.contains(r#"#define RECOMP_MODULE_NAME       "we\"ird\\mod\x7F""#));
    }

    #[test]
    fn zero_ctor_module_emits_zero_probe() {
        let mut f = patapon_facts();
        f.ctor_count = 0;
        f.first_ctor = 0;
        let h = emit_module_header(&f);
        assert!(h.contains("#define RECOMP_CTOR_COUNT        0U\n"));
        assert!(h.contains("#define RECOMP_FIRST_CTOR        0x00000000U"));
    }
}
