//! `output/syscall_table.cpp` — generated NID import binding table (issue #40).
//!
//! One `RecompNidStub` row per analysis.json `imports[]` entry
//! (stub address → module + NID → resolved name). The runtime's
//! `psp_hle_init()` walks this table and registers its HLE handlers BY NAME
//! against the stub addresses, replacing the hand-maintained
//! `runtime/include/hle/psp_hle_syscall_table.h` that only ever described
//! Patapon. NID-database misses keep their `NID_0x%08X` fallback name — they
//! never bind to a handler, so the runtime gives them a loud unimplemented
//! stub instead (never silent).
//!
//! Deterministic: rows are sorted by stub address. The header comment carries
//! the SHA-256 of the source analysis.json (same hash recipe as
//! `fingerprint.json`'s `analysis.sha256`) so a table can always be traced
//! back to its input.

use psp_parser::analysis_json::JsonImport;

/// One parsed row, pre-sorted for emission.
struct Row {
    stub_addr: u32,
    nid: u32,
    name: String,
    module: String,
}

/// Escape a name for a C string literal (NID-db names are ASCII identifiers
/// in practice, but the module names come from binary data — never trust it).
fn c_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            c if (' '..='~').contains(&c) => out.push(c),
            c => {
                for b in c.to_string().bytes() {
                    out.push_str(&format!("\\x{b:02X}"));
                }
            }
        }
    }
    out
}

fn parse_hex(field: &str, what: &str) -> anyhow::Result<u32> {
    u32::from_str_radix(field.trim_start_matches("0x").trim_start_matches("0X"), 16)
        .map_err(|e| anyhow::anyhow!("imports[] {what} \"{field}\" is not a hex address: {e}"))
}

/// Render `syscall_table.cpp` from analysis.json `imports[]`.
///
/// `analysis_sha256`: lowercase-hex SHA-256 of the analysis.json file (the
/// fingerprint module's recipe). Errors are actionable: a malformed
/// `imports[]` entry names the offending field instead of being skipped.
pub fn emit_syscall_table(
    imports: &[JsonImport],
    analysis_sha256: &str,
) -> anyhow::Result<String> {
    let mut rows: Vec<Row> = imports
        .iter()
        .map(|imp| {
            Ok(Row {
                stub_addr: parse_hex(&imp.stub_addr, "stub_addr")?,
                nid: parse_hex(&imp.nid, "nid")?,
                name: imp.name.clone(),
                module: imp.module_name.clone(),
            })
        })
        .collect::<anyhow::Result<Vec<Row>>>()?;
    rows.sort_by_key(|r| r.stub_addr);

    let mut modules: Vec<&str> = rows.iter().map(|r| r.module.as_str()).collect();
    modules.sort_unstable();
    modules.dedup();

    let mut out = String::with_capacity(rows.len() * 96 + 1024);
    out.push_str(&format!(
        "// Generated by `psprecomp recompile` (issue #40). DO NOT EDIT.\n\
         // NID import binding table: {} import stub(s) from {} librar{}.\n\
         // Source analysis.json sha256: {}\n\
         //\n\
         // The runtime's psp_hle_init() binds HLE handlers by func_name and\n\
         // registers them in the dispatch table at stub_addr; rows whose name\n\
         // has no registered handler get a loud unimplemented stub. Unresolved\n\
         // NIDs keep their NID_0x%08X fallback name (see recompile_report.json\n\
         // unresolved_nids[]).\n\
         #include <cstdint>\n\n",
        rows.len(),
        modules.len(),
        if modules.len() == 1 { "y" } else { "ies" },
        analysis_sha256,
    ));
    out.push_str(
        "extern \"C\" {\n\
         typedef struct RecompNidStub {\n\
        \x20   uint32_t stub_addr;\n\
        \x20   uint32_t nid;\n\
        \x20   const char* func_name;\n\
        \x20   const char* module_name;\n\
         } RecompNidStub;\n\
         extern const RecompNidStub recomp_nid_stubs[];\n\
         extern const int recomp_nid_stub_count;\n\
         }\n\n",
    );
    // C++ forbids zero-length arrays: an import-free analysis still gets one
    // sentinel row, excluded by the count the runtime iterates with.
    out.push_str("extern const RecompNidStub recomp_nid_stubs[] = {\n");
    if rows.is_empty() {
        out.push_str("    { 0x00000000U, 0x00000000U, nullptr, nullptr }, // sentinel: no imports\n");
    }
    for r in &rows {
        out.push_str(&format!(
            "    {{ 0x{:08X}U, 0x{:08X}U, \"{}\", \"{}\" }},\n",
            r.stub_addr,
            r.nid,
            c_escape(&r.name),
            c_escape(&r.module),
        ));
    }
    out.push_str(&format!(
        "}};\nextern const int recomp_nid_stub_count = {};\n",
        rows.len()
    ));
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn imp(stub: &str, nid: &str, name: &str, module: &str) -> JsonImport {
        JsonImport {
            nid: nid.into(),
            stub_addr: stub.into(),
            name: name.into(),
            module_name: module.into(),
        }
    }

    #[test]
    fn emits_sorted_rows_count_and_hash() {
        let imports = vec![
            imp("0x089D7530", "0xFB8E22EC", "sceKernelEnableSubIntr", "InterruptManager"),
            imp("0x089D7520", "0xCA04A2B9", "sceKernelRegisterSubIntrHandler", "InterruptManager"),
        ];
        let cpp = emit_syscall_table(&imports, "abc123").unwrap();
        assert!(cpp.contains("Source analysis.json sha256: abc123"));
        assert!(cpp.contains("extern const int recomp_nid_stub_count = 2;"));
        // Sorted by stub address, not input order
        let first = cpp.find("0x089D7520U").unwrap();
        let second = cpp.find("0x089D7530U").unwrap();
        assert!(first < second);
        assert!(cpp.contains(
            "{ 0x089D7520U, 0xCA04A2B9U, \"sceKernelRegisterSubIntrHandler\", \"InterruptManager\" },"
        ));
    }

    #[test]
    fn unresolved_nid_keeps_fallback_name() {
        let imports = vec![imp("0x08C00008", "0xDEADBEEF", "NID_0xDEADBEEF", "scesupPreAcc")];
        let cpp = emit_syscall_table(&imports, "h").unwrap();
        assert!(cpp.contains("\"NID_0xDEADBEEF\", \"scesupPreAcc\""));
    }

    #[test]
    fn empty_imports_emit_sentinel_with_zero_count() {
        let cpp = emit_syscall_table(&[], "h").unwrap();
        assert!(cpp.contains("sentinel: no imports"));
        assert!(cpp.contains("extern const int recomp_nid_stub_count = 0;"));
    }

    #[test]
    fn malformed_hex_is_an_actionable_error() {
        let imports = vec![imp("not-hex", "0x1", "x", "m")];
        let err = emit_syscall_table(&imports, "h").unwrap_err().to_string();
        assert!(err.contains("stub_addr"), "error should name the field: {err}");
        assert!(err.contains("not-hex"));
    }

    #[test]
    fn module_names_are_escaped() {
        let imports = vec![imp("0x08C00000", "0x1", "f", "bad\"mod\\")];
        let cpp = emit_syscall_table(&imports, "h").unwrap();
        assert!(cpp.contains("\"bad\\\"mod\\\\\""));
    }
}
